filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/access.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "filebeat-nginx-%{+yyyy.MM.dd}"

setup.template.name: "filebeat-nginx"
setup.template.pattern: "filebeat-nginx-*"
setup.ilm.enabled: false
